### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by achourasia**
Cleaned up the description and page title

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks!

**Comment by achourasia** [comment]
http://sciviscontest.ieeevis.org has been getting 404, perhaps this will get pushed out soon. Please check

**Comment by cscheid** [comment]
Yes, I'm working on this right now.

**Comment by cscheid** [comment]
Content is being uploaded to sciviscontest.ieeevis.org right now.

**Comment by achourasia** [comment]
Its up now. Thanks

**Pull request merged**
